name: ecd_restaurant
description: A new Flutter project for Restaurant App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  socket_io_client: ^3.1.4
  shared_preferences: ^2.5.5
  audioplayers: ^6.7.1
  image_picker: ^1.2.3
  google_fonts: ^6.1.0
  firebase_core: ^4.13.0
  firebase_crashlytics: ^5.2.7
  firebase_analytics: ^12.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "web/icons/logo.png"

flutter:
  uses-material-design: true
  assets:
    - splash_logo.png
    - image.png
    - ecdkart_logo.png
    - assets/audio/
    - assets/images/
    - assets/images/image.png
    - assets/images/splash_logo.png
    - assets/images/ecdkart_logo.png
    - assets/images/ecdkart_pill_logo.png
    - assets/images/restaurant_butterchicken_header.jpg
    - assets/images/restaurant_chicken_item.jpg
    - assets/images/restaurant_chinese_header.jpg
    - assets/images/restaurant_daltadka_header.jpg
    - assets/images/restaurant_handibiryani_header.jpg
    - assets/images/restaurant_header_bg.jpg
    - assets/images/restaurant_legpiece_header.jpg
    - assets/images/restaurant_login_header.jpg
    - assets/images/restaurant_nonveg_header.jpg
    - assets/images/restaurant_otp_header.jpg
    - assets/images/restaurant_paneertikka_header.jpg
    - assets/images/restaurant_pizza_item.jpg
    - assets/images/restaurant_top_header_bg.jpg
    - assets/images/restaurant_menu_header_bg.jpg
    - assets/images/restaurant_order_header.jpg
    - assets/images/welcome_back.png
