// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANprYbD67VkVV5dw-d1ApJOWPEKNNpQbo',
    appId: '1:168004879111:web:2641bc37ce230379263ba2',
    messagingSenderId: '168004879111',
    projectId: 'ecdkart-24dbe',
    authDomain: 'ecdkart-24dbe.firebaseapp.com',
    storageBucket: 'ecdkart-24dbe.firebasestorage.app',
    measurementId: 'G-TRSH5DNHZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2tG-AvxvzlEX-Wd0Ej17Pf4cjBuzYKnw',
    appId: '1:168004879111:android:bf63dafeef6691a3263ba2',
    messagingSenderId: '168004879111',
    projectId: 'ecdkart-24dbe',
    storageBucket: 'ecdkart-24dbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjEqhW74292IN8fvmycPa6_KLAHdoTbZA',
    appId: '1:168004879111:ios:7fb5463c5c11170f263ba2',
    messagingSenderId: '168004879111',
    projectId: 'ecdkart-24dbe',
    storageBucket: 'ecdkart-24dbe.firebasestorage.app',
    iosBundleId: 'com.example.ectkart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjEqhW74292IN8fvmycPa6_KLAHdoTbZA',
    appId: '1:168004879111:ios:7fb5463c5c11170f263ba2',
    messagingSenderId: '168004879111',
    projectId: 'ecdkart-24dbe',
    storageBucket: 'ecdkart-24dbe.firebasestorage.app',
    iosBundleId: 'com.example.ectkart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANprYbD67VkVV5dw-d1ApJOWPEKNNpQbo',
    appId: '1:168004879111:web:fb3690a8b48447fd263ba2',
    messagingSenderId: '168004879111',
    projectId: 'ecdkart-24dbe',
    authDomain: 'ecdkart-24dbe.firebaseapp.com',
    storageBucket: 'ecdkart-24dbe.firebasestorage.app',
    measurementId: 'G-FSY2LFPZT7',
  );
}
